# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'cloud_demo_foundational'
version: '1.0.0'
config-version: 2
profile: penny_fusion_migration


# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
  - "dbt_packages"

dbt-cloud:
  project-id: 381671

vars:
  start_date: '1999-01-01'
  dev_targets: ['dev', 'default']
  dynamic_start_time: '{{ microbatch_begin() }}'

flags:
  require_model_names_without_spaces: true

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

  require_generic_test_arguments_property: true
models:
  +static_analysis: off
  cloud_demo_foundational:
    staging:
      +materialized: view
      +static_analysis: off
      tpch:
        +tags: "pii"

    marts:
      core:
        +materialized: table
        +group: sales
        +static_analysis: off