with 

source as (

    select * from {{ source('stocks', 'balance_sheet') }}

),

renamed as (

    select
        symbol,
        asofdate as date,
        periodtype as period_type,
        currencycode as currency_code,
        accountspayable as accounts_payable,
        accountsreceivable as accounts_receivable,
        accruedinterestreceivable as accrued_interest_receivable,
        accumulateddepreciation as accumulated_depreciation,
        additionalpaidincapital as additional_paid_in_capital,
        allowancefordoubtfulaccountsreceivable as allowance_for_doubtful_accounts_receivable,
        assetsheldforsalecurrent as assets_held_for_sale_current,
        availableforsalesecurities as available_for_sale_securities,
        buildingsandimprovements as buildings_and_improvements,
        capitalleaseobligations as capital_lease_obligations,
        capitalstock as capital_stock,
        cashandcashequivalents as cash_and_cash_equivalents,
        cashcashequivalentsandshortterminvestments as cash_cash_equivalents_and_short_term_investments,
        cashequivalents as cash_equivalents,
        cashfinancial as cash_financial,
        commercialpaper as commercial_paper,
        commonstock as common_stock,
        commonstockequity as common_stock_equity,
        constructioninprogress as construction_in_progress,
        currentaccruedexpenses as current_accrued_expenses,
        currentassets as current_assets,
        currentcapitalleaseobligation as current_capital_lease_obligation,
        currentdebt as current_debt,
        currentdebtandcapitalleaseobligation as current_debt_and_capital_lease_obligation,
        currentdeferredassets as current_deferred_assets,
        currentdeferredliabilities as current_deferred_liabilities,
        currentdeferredrevenue as current_deferred_revenue,
        currentdeferredtaxesassets as current_deferred_taxes_assets,
        currentdeferredtaxesliabilities as current_deferred_taxes_liabilities,
        currentliabilities as current_liabilities,
        currentnotespayable as current_notes_payable,
        currentprovisions as current_provisions,
        definedpensionbenefit as defined_pension_benefit,
        derivativeproductliabilities as derivative_product_liabilities,
        dividendspayable as dividends_payable,
        duefromrelatedpartiescurrent as due_from_related_parties_current,
        duefromrelatedpartiesnoncurrent as due_from_related_parties_non_current,
        duetorelatedpartiescurrent as due_to_related_parties_current,
        duetorelatedpartiesnoncurrent as due_to_related_parties_non_current,
        employeebenefits as employee_benefits,
        financialassets as financial_assets,
        financialassetsdesignatedasfairvaluethroughprofitorlosstotal as financial_assets_designated_as_fair_value_through_profit_or_loss_total,
        finishedgoods as finished_goods,
        foreigncurrencytranslationadjustments as foreign_currency_translation_adjustments,
        gainslossesnotaffectingretainedearnings as gains_losses_not_affecting_retained_earnings,
        goodwill,
        goodwillandotherintangibleassets as goodwill_and_other_intangible_assets,
        grossaccountsreceivable as gross_accounts_receivable,
        grossppe as gross_ppe,
        hedgingassetscurrent as hedging_assets_current,
        heldtomaturitysecurities as held_to_maturity_securities,
        incometaxpayable as income_tax_payable,
        interestpayable as interest_payable,
        inventoriesadjustmentsallowances as inventories_adjustments_allowances,
        inventory as inventory,
        investedcapital as invested_capital,
        investmentproperties as investment_properties,
        investmentinfinancialassets as investment_in_financial_assets,
        investmentsandadvances as investments_and_advances,
        investmentsinotherventuresunderequitymethod as investments_in_other_ventures_under_equity_method,
        investmentsinassociatesatcost as investments_in_associates_at_cost,
        investmentsinjointventuresatcost as investments_in_joint_ventures_at_cost,
        investmentsinsubsidiariesatcost as investments_in_subsidiaries_at_cost,
        landandimprovements as land_and_improvements,
        leases,
        liabilitiesheldforsalenoncurrent as liabilities_held_for_sale_non_current,
        lineofcredit as line_of_credit,
        loansreceivable as loans_receivable,
        longtermcapitalleaseobligation as long_term_capital_lease_obligation,
        longtermdebt as long_term_debt,
        longtermdebtandcapitalleaseobligation as long_term_debt_and_capital_lease_obligation,
        longtermequityinvestment as long_term_equity_investment,
        longtermprovisions as long_term_provisions,
        machineryfurnitureequipment as machinery_furniture_equipment,
        minimumpensionliabilities as minimum_pension_liabilities,
        minorityinterest as minority_interest,
        netdebt as net_debt,
        netppe as net_ppe,
        nettangibleassets as net_tangible_assets,
        noncurrentaccountsreceivable as non_current_accounts_receivable,
        noncurrentaccruedexpenses as non_current_accrued_expenses,
        noncurrentdeferredassets as non_current_deferred_assets,
        noncurrentdeferredliabilities as non_current_deferred_liabilities,
        noncurrentdeferredrevenue as non_current_deferred_revenue,
        noncurrentdeferredtaxesassets as non_current_deferred_taxes_assets,
        noncurrentdeferredtaxesliabilities as non_current_deferred_taxes_liabilities,
        noncurrentnotereceivables as non_current_note_receivables,
        noncurrentpensionandotherpostretirementbenefitplans as non_current_pension_and_other_post_retirement_benefit_plans,
        noncurrentprepaidassets as non_current_prepaid_assets,
        notesreceivable as notes_receivable,
        ordinarysharesnumber as ordinary_shares_number,
        othercurrentassets as other_current_assets,
        othercurrentborrowings as other_current_borrowings,
        othercurrentliabilities as other_current_liabilities,
        otherequityadjustments as other_equity_adjustments,
        otherequityinterest as other_equity_interest,
        otherintangibleassets as other_intangible_assets,
        otherinventories as other_inventories,
        otherinvestments as other_investments,
        othernoncurrentassets as other_non_current_assets,
        othernoncurrentliabilities as other_non_current_liabilities,
        otherpayable as other_payable,
        otherproperties as other_properties,
        otherreceivables as other_receivables,
        othershortterminvestments as other_short_term_investments,
        payables,
        payablesandaccruedexpenses as payables_and_accrued_expenses,
        pensionandotherpostretirementbenefitplanscurrent as pension_and_other_post_retirement_benefit_plans_current,
        preferredsecuritiesoutsidestockequity as preferred_securities_outside_stock_equity,
        preferredsharesnumber as preferred_shares_number,
        preferredstock as preferred_stock,
        preferredstockequity as preferred_stock_equity,
        prepaidassets as prepaid_assets,
        properties,
        rawmaterials,
        receivables,
        receivablesadjustmentsallowances as receivables_adjustments_allowances,
        restrictedcash as restricted_cash,
        retainedearnings as retained_earnings,
        shareissued as share_issued,
        stockholdersequity as stockholders_equity,
        tangiblebookvalue as tangible_book_value,
        taxesreceivable as taxes_receivable,
        totalassets as total_assets,
        totalcapitalization as total_capitalization,
        totaldebt as total_debt,
        totalequitygrossminorityinterest as total_equity_gross_minority_interest,
        totalliabilitiesnetminorityinterest as total_liabilities_net_minority_interest,
        totalnoncurrentassets as total_non_current_assets,
        totalnoncurrentliabilitiesnetminorityinterest as total_non_current_liabilities_net_minority_interest,
        totaltaxpayable as total_tax_payable,
        tradeandotherpayablesnoncurrent as trade_and_other_payables_non_current,
        tradingsecurities as trading_securities,
        treasurysharesnumber as treasury_shares_number,
        treasurystock as treasury_stock,
        unrealizedgainloss as unrealized_gain_loss,
        workinprocess as work_in_process,
        workingcapital as working_capital,
        restrictedcommonstock as restricted_common_stock
    from source


)

select * from renamed
